# Generated by Django 4.1 on 2022-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("P", "Pants"),
                    ("D", "Dress"),
                    ("SU", "Suits"),
                ],
                default="S",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
