# Generated by Django 4.1 on 2022-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pants"),
                    ("D", "Dress"),
                    ("S", "Shirt"),
                    ("SU", "Suits"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
