# Generated by Django 4.1 on 2022-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_categories_alter_item_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories", old_name="category", new_name="title",
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Shirt"),
                    ("D", "Dress"),
                    ("SU", "Suits"),
                    ("P", "Pants"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
